name: Notebook checks

on:
  push:
    paths-ignore:
    - "run.py"
  schedule:
    # Every 3 hours
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */3 * * *'

jobs:
  rerun:
    # If you change this job, please also change it in
    # build_runner.yaml (and see comments there for explanation)
    runs-on: ubuntu-latest
    name: Test notebooks are runnable and up-to-date
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      uses: ./.github/actions/build
      with:
        args: jupyter nbconvert --to notebook --execute /home/app/notebook/covid-mortality-by-testing.ipynb --output /home/app/notebook/covid-mortality-by-testing.ipynb./run_tests.sh
